---
- name: install git
  apt:
    name: git
    state: present

- name: install python3
  become: yes
  become_user: root
  apt:
    name: python3
    state: present

- name: install pip
  become: yes
  become_user: root
  apt:
    name: python3-pip
    state: present

- name: install libffi
  become: yes
  become_user: root
  apt:
    name: libffi-dev
    state: present

- name: install libssl
  become: yes
  become_user: root
  apt:
    name: libssl-dev
    state: present

- name: install python3-dev
  become: yes
  become_user: root
  apt:
    name: python3-dev
    state: present

- name: check if docker is installed
  command: systemctl status docker
  register: docker_check
  ignore_errors: yes

- name: install docker
  become: yes
  become_user: root
  shell:
    cmd: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
  when:
    docker_check.stdout.find('No such file') != -1

- name: install docker-compose
  become: yes
  become_user: root
  shell:
    cmd: pip3 install docker-compose